export const actionTypes = {
  FETCH_DATA_START: "FETCH_DATA_START",
  FETCH_DATA_END: "FETCH_DATA_END",
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  FETCH_DATA_ERROR: "FETCH_DATA_ERROR",
  USER_LOCATION: "USER_LOCATION",
  USER_WEATHER: " USER_WEATHER",
};
